services:
  market-alpha-api:
    build: .
    command: ["uvicorn", "api.main:app", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "18000:8000"
    networks:
      - market-alpha-scanner-private
    environment:
      - DATABASE_URL=postgresql://market_alpha:market_alpha@market-alpha-postgres/market_alpha

networks:
  market-alpha-scanner-private: {}
