"""use bigint for price_history volume

Revision ID: a1b2c3d4e5f6
Revises: 20260423_010000
Create Date: 2023-10-28 10:00:00.000000

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "20260423_010000"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price_history", "volume", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price_history", "volume", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    # ### end Alembic commands ###
